### ISSUE TITLE
Doesn't produce coverage

### ISSUE THREAD

**Issue by fudini** [deepsweet/istanbul-instrumenter-loader#4]
I only get coverage report on files that are imported in test files.
How does it know where are all my source files that need to be checked since it's not set up in config?

**Comment by arantir** [comment]
It's just a webpack loader, so knows only the files the webpack does.

Development utilities for ES6 is not so perfect now, until ES6 isn't mature.

However, you may try this config:
```javascript
    files: [
      "src/entry.js", // The entry point of your app. The same is used in your webpack config.
      "test/**/*_test.js"
    ],
```

In this case the loader will process the whole application and you will get a complete coverage report. Although tests will still "webpacked" and load separately (preserving modules dependencies in tests and etc.).
Because coverage report is a summary of runs-by-line, all the latter runs of tests will fulfill the eventual report.

**Comment by fudini** [comment]
Thanks @arantir. My problem was that the library doesn't have any entry point that would ensure that all files are loaded. I fixed it by loading all files into a webpack context in my main spec file.
